%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/john/Datasets/data_odometry_gray/dataset/sequences/07
inertial_dir: /home/john/Datasets/2011_09_30_drive_0027_extract/2011_09_30/2011_09_30_drive_0027_extract/oxts


# IMU
#Accelerometers
imu.accelerometer_noise_density: 0.01
imu.accelerometer_random_walk: 0.000167
#Gyroscopes
imu.gyroscope_noise_density: 0.000175
imu.gyroscope_random_walk: 2.91e-006
#Frequency
imu.frequency: 100

NUM_KFs_FOR_IMU_INIT: 5

WINDOW_SIZE_FOR_ACTIVE_KFS: 10
RATIO_OF_TRACKED_MP_FOR_NEW_KFS: 0.75

keyframeTimeGapTracking: 0.5

threshold_fast_detector: 50
num_features_init: 100
num_features_tracking_good: 20
num_features_needed_for_keyframe: 80
